/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.programacion.paint.ventana;
import com.programacion.paint.clases.Pincel;
import com.programacion.paint.clases.PincelBasico;
import com.programacion.paint.clases.PincelContinuo;
import com.programacion.paint.clases.PincelEstrella;
import com.programacion.paint.clases.PincelGordo;
import com.programacion.paint.clases.PincelRectangulo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author jose_
 */
public class frmPaint extends javax.swing.JFrame {

        /**
         * Creates new form frmPaint
         */
        
        private BufferedImage lienzo;
        
        public frmPaint() {
                initComponents();
                this.lienzo = null;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jtbBotones = new javax.swing.JToolBar();
                cmdNuevo = new javax.swing.JButton();
                cmdGuardar = new javax.swing.JButton();
                cmdAbrir = new javax.swing.JButton();
                cmdColor = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                cmbPinceles = new javax.swing.JComboBox<>();
                lblAreaDibujo = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Paint (C) 2022 Jose Almiron");
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                jtbBotones.setRollover(true);

                cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/programacion/paint/recursos/nuevo.png"))); // NOI18N
                cmdNuevo.setFocusable(false);
                cmdNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                cmdNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdNuevoActionPerformed(evt);
                        }
                });
                jtbBotones.add(cmdNuevo);

                cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/programacion/paint/recursos/guardar.png"))); // NOI18N
                cmdGuardar.setFocusable(false);
                cmdGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                cmdGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdGuardarActionPerformed(evt);
                        }
                });
                jtbBotones.add(cmdGuardar);

                cmdAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/programacion/paint/recursos/abrir.png"))); // NOI18N
                cmdAbrir.setFocusable(false);
                cmdAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                cmdAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                cmdAbrir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdAbrirActionPerformed(evt);
                        }
                });
                jtbBotones.add(cmdAbrir);

                cmdColor.setBackground(new java.awt.Color(255, 255, 255));
                cmdColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/programacion/paint/recursos/color.png"))); // NOI18N
                cmdColor.setFocusable(false);
                cmdColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                cmdColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                cmdColor.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdColorActionPerformed(evt);
                        }
                });
                jtbBotones.add(cmdColor);

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/programacion/paint/recursos/lapiz.png"))); // NOI18N

                cmbPinceles.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cmbPincelesItemStateChanged(evt);
                        }
                });

                lblAreaDibujo.setBackground(new java.awt.Color(0, 0, 0));
                lblAreaDibujo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
                lblAreaDibujo.setOpaque(true);
                lblAreaDibujo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                lblAreaDibujoMouseDragged(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtbBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addGap(3, 3, 3)
                                                .addComponent(cmbPinceles, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblAreaDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtbBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbPinceles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAreaDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                rellenarPinceles();
                nuevaImagen();
        }//GEN-LAST:event_formWindowOpened

        private void lblAreaDibujoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreaDibujoMouseDragged
                Pincel p = (Pincel) cmbPinceles.getSelectedItem();
                Graphics lapiz = this.lienzo.getGraphics();
                lapiz.setColor(cmdColor.getBackground());
                p.dibujar(lapiz, evt.getPoint());
                actualizarPantalla();
        }//GEN-LAST:event_lblAreaDibujoMouseDragged

        private void cmbPincelesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPincelesItemStateChanged
                Pincel p = (Pincel) cmbPinceles.getSelectedItem();
                p.resetar();
        }//GEN-LAST:event_cmbPincelesItemStateChanged

        private void cmdColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdColorActionPerformed
                Color color = JColorChooser.showDialog(null, "Selecciona un color", Color.WHITE);
                cmdColor.setBackground(color);
        }//GEN-LAST:event_cmdColorActionPerformed

        private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
                nuevaImagen();
        }//GEN-LAST:event_cmdNuevoActionPerformed

        private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
                JFileChooser fileChooser = new JFileChooser();
                if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                        try {
                                File file = fileChooser.getSelectedFile();
                                ImageIO.write(this.lienzo, "jpeg", file);
                                JOptionPane.showMessageDialog(this, "Imagen guardada correctamente", "", JOptionPane.INFORMATION_MESSAGE);
                        } catch (IOException ex) {
                                JOptionPane.showMessageDialog(this, "La imagen no se ha podido guardar", "Error", JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(frmPaint.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }//GEN-LAST:event_cmdGuardarActionPerformed

        private void cmdAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbrirActionPerformed
                 JFileChooser fileChooser = new JFileChooser();
                if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                        try {
                                File file = fileChooser.getSelectedFile();
                                this.lienzo = ImageIO.read(file);
                                actualizarPantalla();
                        } catch (IOException ex) {
                                JOptionPane.showMessageDialog(this, "La imagen no se ha podido guardar", "Error", JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(frmPaint.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }//GEN-LAST:event_cmdAbrirActionPerformed

        /**
         * @param args the command line arguments
         */
        
        private void nuevaImagen() {
                int alto = lblAreaDibujo.getHeight();
                int ancho = lblAreaDibujo.getWidth();
                this.lienzo = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_RGB);
                actualizarPantalla();
        }
        
        private void actualizarPantalla() {
                Graphics lapiz = lblAreaDibujo.getGraphics();
                lapiz.drawImage(this.lienzo, 0, 0, null);
        }
        
        private void rellenarPinceles() {              
                PincelBasico basico = new PincelBasico();
                PincelContinuo continuo = new PincelContinuo();
                PincelGordo gordo = new PincelGordo();
                PincelRectangulo rectangulo = new PincelRectangulo();
                PincelEstrella estrella = new PincelEstrella();
                cmbPinceles.addItem(basico);
                cmbPinceles.addItem(continuo);
                cmbPinceles.addItem(gordo);
                cmbPinceles.addItem(rectangulo);
                cmbPinceles.addItem(estrella);
        }
        
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try
                {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                        {
                                if ("Nimbus".equals(info.getName()))
                                {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex)
                {
                        java.util.logging.Logger.getLogger(frmPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex)
                {
                        java.util.logging.Logger.getLogger(frmPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex)
                {
                        java.util.logging.Logger.getLogger(frmPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex)
                {
                        java.util.logging.Logger.getLogger(frmPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new frmPaint().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<Pincel> cmbPinceles;
        private javax.swing.JButton cmdAbrir;
        private javax.swing.JButton cmdColor;
        private javax.swing.JButton cmdGuardar;
        private javax.swing.JButton cmdNuevo;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JToolBar jtbBotones;
        private javax.swing.JLabel lblAreaDibujo;
        // End of variables declaration//GEN-END:variables
}
